import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KEEMTHI BAATEIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         قیمتی بیانات
        </h1>
        <h1 className={styles.h1}> KEEMTHI BAYAANAATH</h1>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Links for Bayaans &rarr;</h2>
            <Link href='/bayaanaath'><p className={styles.description}>Important Bayaans from Buzurgaan-E-Deen{' '}.</p></Link>
          </a>

          <a href="" className={styles.card}>
            <h2>English Content &rarr;</h2>
            <Link href="/englishcontent"><p className={styles.description}>All the content is in English in PDF format. </p></Link>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Urdu Content &rarr;</h2>
            <Link href="/urducontent"><p className={styles.description}>All the content is in Urdu in PDF format. </p></Link>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Images & clips &rarr;</h2>
            <p className={styles.description}>
             Pictures and sound clips of important bayaans.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a className={styles.h1}
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Website created by IDN
        </a>
      </footer>
    </div>
  )
}
